/**
 * LLM-as-judge helpers for toprank evals.
 *
 * Provides:
 * - callJudge     — generic JSON-from-LLM helper
 * - judge         — SKILL.md quality scorer (clarity/completeness/actionability)
 * - seoReportJudge — SEO report quality scorer
 *
 * Requires: ANTHROPIC_API_KEY env var.
 * Adapted from garrytan/gstack llm-judge.ts.
 */

import Anthropic from '@anthropic-ai/sdk';

export interface JudgeScore {
  clarity: number;       // 1–5: can an agent understand what to do?
  completeness: number;  // 1–5: is all needed info present?
  actionability: number; // 1–5: can an agent act without guessing?
  reasoning: string;
}

export interface SeoReportScore {
  has_quick_wins: boolean;       // Report includes a Quick Wins section
  recommendations_specific: boolean; // Recommendations include specific page URLs and query names
  has_action_plan: boolean;      // Report includes a 30-day action plan table
  quantified_impact: boolean;    // At least one recommendation includes estimated click/traffic impact
  score: number;                 // 1–5 overall quality
  reasoning: string;
}

/**
 * Call claude-sonnet-4-6, return parsed JSON. Retries once on 429.
 */
export async function callJudge<T>(prompt: string): Promise<T> {
  const client = new Anthropic();

  const makeRequest = () =>
    client.messages.create({
      model: 'claude-sonnet-4-6',
      max_tokens: 1024,
      messages: [{ role: 'user', content: prompt }],
    });

  let response;
  try {
    response = await makeRequest();
  } catch (err: any) {
    if (err.status === 429) {
      await new Promise(r => setTimeout(r, 2000));
      response = await makeRequest();
    } else {
      throw err;
    }
  }

  const text = response.content[0].type === 'text' ? response.content[0].text : '';
  const match = text.match(/\{[\s\S]*\}/);
  if (!match) throw new Error(`Judge returned non-JSON: ${text.slice(0, 200)}`);
  return JSON.parse(match[0]) as T;
}

/**
 * Score a SKILL.md section for documentation quality.
 * An agent reads this to understand what to do — we're checking whether
 * the instructions are clear, complete, and actionable enough to follow.
 */
export async function judge(section: string, content: string): Promise<JudgeScore> {
  return callJudge<JudgeScore>(`You are evaluating instructions for an AI agent performing SEO analysis.

The agent reads these instructions to learn how to run a structured SEO audit. It needs to:
1. Know what steps to take and in what order
2. Know what tools/scripts to call and with what arguments
3. Know what the output should look like and what to include

Rate the following ${section} on three dimensions (1–5):

- **clarity** (1–5): Can an agent understand what each step does from the description alone?
- **completeness** (1–5): Are commands, arguments, and expected behavior documented? Would an agent need to guess anything?
- **actionability** (1–5): Can an agent execute this section correctly without asking follow-up questions?

Scoring guide:
- 5: Excellent — no ambiguity, all info present
- 4: Good — minor gaps an experienced agent can infer
- 3: Adequate — some guessing required
- 2: Poor — significant info missing
- 1: Unusable — agent would fail without external help

Respond with ONLY valid JSON:
{"clarity": N, "completeness": N, "actionability": N, "reasoning": "brief explanation"}

Content to evaluate:

${content}`);
}

/**
 * Evaluate a generated SEO report against quality criteria.
 * Checks for structural completeness and recommendation specificity.
 */
export async function seoReportJudge(report: string): Promise<SeoReportScore> {
  return callJudge<SeoReportScore>(`You are evaluating the quality of an SEO analysis report generated by an AI agent.

A high-quality SEO report must:
1. Include a "Quick Wins" section with specific page URLs and query names
2. Make recommendations that are specific and actionable (not vague like "improve your SEO")
3. Include a 30-day action plan with prioritized steps
4. Quantify expected impact (e.g. estimated click increases) for at least one recommendation

Evaluate the following report:

---
${report.slice(0, 6000)}
---

Respond with ONLY valid JSON:
{
  "has_quick_wins": true/false,
  "recommendations_specific": true/false,
  "has_action_plan": true/false,
  "quantified_impact": true/false,
  "score": 1-5,
  "reasoning": "brief explanation"
}
`);
}
