"""
LLM-as-judge helpers for toprank evals.

Requires: ANTHROPIC_API_KEY env var and `anthropic` package installed.
"""

import json
import re
import time
from dataclasses import dataclass

_client = None


def _get_client():
    global _client
    if _client is None:
        try:
            import anthropic
        except ImportError:
            raise ImportError(
                'anthropic package required for LLM judge — run: pip install anthropic'
            )
        _client = anthropic.Anthropic()
    return _client


def call_judge(prompt: str) -> dict:
    """Call claude-sonnet-4-6, return parsed JSON. Retries up to 3 times on rate limit."""
    client = _get_client()

    def make_request():
        return client.messages.create(
            model='claude-sonnet-4-6',
            max_tokens=1024,
            messages=[{'role': 'user', 'content': prompt}],
        )

    last_exc: Exception | None = None
    for attempt in range(3):
        try:
            response = make_request()
            break
        except Exception as e:
            if getattr(e, 'status_code', None) == 429 or 'rate' in str(e).lower():
                last_exc = e
                time.sleep(2 ** attempt)  # 1s, 2s, 4s
            else:
                raise
    else:
        raise last_exc  # all retries exhausted

    text = response.content[0].text if response.content[0].type == 'text' else ''
    match = re.search(r'\{[\s\S]*\}', text)
    if not match:
        raise ValueError(f'Judge returned non-JSON: {text[:200]}')
    return json.loads(match.group(0))


@dataclass
class JudgeScore:
    clarity: int        # 1–5: can an agent understand what to do?
    completeness: int   # 1–5: is all needed info present?
    actionability: int  # 1–5: can an agent act without guessing?
    reasoning: str


@dataclass
class SeoReportScore:
    has_quick_wins: bool           # Report includes a Quick Wins section
    recommendations_specific: bool # Recommendations include specific URLs and query names
    has_action_plan: bool          # Report includes a 30-day action plan
    quantified_impact: bool        # At least one recommendation quantifies impact
    score: int                     # 1–5 overall quality
    reasoning: str


def judge(section: str, content: str) -> JudgeScore:
    """Score a SKILL.md section for documentation quality."""
    result = call_judge(f"""You are evaluating instructions for an AI agent performing SEO analysis.

The agent reads these instructions to learn how to run a structured SEO audit. It needs to:
1. Know what steps to take and in what order
2. Know what tools/scripts to call and with what arguments
3. Know what the output should look like and what to include

Rate the following {section} on three dimensions (1–5):

- **clarity** (1–5): Can an agent understand what each step does from the description alone?
- **completeness** (1–5): Are commands, arguments, and expected behavior documented? Would an agent need to guess anything?
- **actionability** (1–5): Can an agent execute this section correctly without asking follow-up questions?

Scoring guide:
- 5: Excellent — no ambiguity, all info present
- 4: Good — minor gaps an experienced agent can infer
- 3: Adequate — some guessing required
- 2: Poor — significant info missing
- 1: Unusable — agent would fail without external help

Respond with ONLY valid JSON:
{{"clarity": N, "completeness": N, "actionability": N, "reasoning": "brief explanation"}}

Content to evaluate:

{content}""")

    return JudgeScore(
        clarity=result['clarity'],
        completeness=result['completeness'],
        actionability=result['actionability'],
        reasoning=result.get('reasoning', ''),
    )


def seo_report_judge(report: str) -> SeoReportScore:
    """Evaluate a generated SEO report against quality criteria."""
    result = call_judge(f"""You are evaluating the quality of an SEO analysis report generated by an AI agent.

A high-quality SEO report must:
1. Include a "Quick Wins" section with specific page URLs and query names
2. Make recommendations that are specific and actionable (not vague like "improve your SEO")
3. Include a 30-day action plan with prioritized steps
4. Quantify expected impact (e.g. estimated click increases) for at least one recommendation

Evaluate the following report:

---
{report[:6000]}
---

Respond with ONLY valid JSON:
{{
  "has_quick_wins": true/false,
  "recommendations_specific": true/false,
  "has_action_plan": true/false,
  "quantified_impact": true/false,
  "score": 1-5,
  "reasoning": "brief explanation"
}}
""")

    return SeoReportScore(
        has_quick_wins=bool(result.get('has_quick_wins')),
        recommendations_specific=bool(result.get('recommendations_specific')),
        has_action_plan=bool(result.get('has_action_plan')),
        quantified_impact=bool(result.get('quantified_impact')),
        score=int(result.get('score', 0)),
        reasoning=result.get('reasoning', ''),
    )
